yet more dev environment changes

diff --git a/docker/develop/Dockerfile b/docker/develop/Dockerfile
--- a/docker/develop/Dockerfile
+++ b/docker/develop/Dockerfile
@@ -1,96 +1,126 @@
-FROM ubuntu:22.04
+ARG PHP_VERSION=8.4
+ARG COMPOSER_VERSION=2.8
+ARG NODE_VERSION=latest
+ARG BUN_VERSION=latest
 
-LABEL maintainer="Taylor Otwell"
+FROM node:${NODE_VERSION} AS node
 
-ARG WWWGROUP=1000
+FROM oven/bun:${BUN_VERSION} AS bun
+
+FROM composer:${COMPOSER_VERSION} AS vendor
+
+FROM php:${PHP_VERSION}-cli-bookworm AS base
+
 ARG WWWUSER=1000
-ARG NODE_VERSION="current"
-ARG POSTGRES_VERSION=17
+ARG WWWGROUP=1000
+ARG TZ=UTC
 
-ENV DEBIAN_FRONTEND=noninteractive
-ENV TZ=UTC
-ENV SUPERVISOR_PHP_USER="sail"
-ENV ROOT="/var/www/html"
+ENV DEBIAN_FRONTEND=noninteractive \
+    TERM=xterm-color \
+    TZ=${TZ} \
+    USER=sail \
+    ROOT=/var/www/html \
+    COMPOSER_FUND=0 \
+    COMPOSER_MAX_PARALLEL_HTTP=24
 
 WORKDIR ${ROOT}
 
-RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
+SHELL ["/bin/bash", "-eou", "pipefail", "-c"]
 
-RUN echo "Acquire::http::Pipeline-Depth 0;" > /etc/apt/apt.conf.d/99custom && \
-    echo "Acquire::http::No-Cache true;" >> /etc/apt/apt.conf.d/99custom && \
-    echo "Acquire::BrokenProxy    true;" >> /etc/apt/apt.conf.d/99custom
+RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime \
+    && echo ${TZ} > /etc/timezone
 
-RUN apt-get update \
-    && mkdir -p /etc/apt/keyrings \
-    && apt-get install -y gnupg2 gosu curl ca-certificates zip unzip git supervisor sqlite3 libcap2-bin libpng-dev python2 dnsutils librsvg2-bin fswatch ffmpeg nano locales wget \
-    && curl -sS 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x14aa40ec0831756756d7f66c4f4ea0aae5267a6c' | gpg --dearmor | tee /etc/apt/keyrings/ppa_ondrej_php.gpg > /dev/null \
-    && echo "deb [signed-by=/etc/apt/keyrings/ppa_ondrej_php.gpg] https://ppa.launchpadcontent.net/ondrej/php/ubuntu jammy main" > /etc/apt/sources.list.d/ppa_ondrej_php.list \
-    && apt-get update \
-    && apt-get install -y php8.4-cli php8.4-dev \
-    php8.4-pgsql php8.4-sqlite3 php8.4-gd \
-    php8.4-curl \
-    php8.4-imap php8.4-mysql php8.4-mbstring \
-    php8.4-xml php8.4-zip php8.4-bcmath php8.4-soap \
-    php8.4-intl php8.4-readline \
-    php8.4-ldap \
-    php8.4-msgpack php8.4-igbinary php8.4-redis php8.4-swoole \
-    php8.4-memcached php8.4-pcov php8.4-imagick php8.4-xdebug \
-    php8.4-excimer \
-    && curl -sLS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer \
-    && curl -sS https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor | tee /etc/apt/keyrings/pgdg.gpg >/dev/null \
-    && echo "deb [signed-by=/etc/apt/keyrings/pgdg.gpg] http://apt.postgresql.org/pub/repos/apt jammy-pgdg main" > /etc/apt/sources.list.d/pgdg.list \
-    && apt-get update \
-    && apt-get install -y mysql-client \
-    && apt-get install -y postgresql-client-$POSTGRES_VERSION \
-    && apt-get install -y ffmpeg build-essential libasound2-dev libpulse-dev lame \
-    && apt-get install -y jpegoptim optipng pngquant gifsicle webp libavif-bin
+ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
+
+RUN dpkg --add-architecture i386; \
+    apt-get update; \
+    apt-get upgrade -yqq; \
+    apt-get install -yqq --no-install-recommends --show-progress \
+    apt-utils \
+    curl \
+    wget \
+    vim \
+    git \
+    ncdu \
+    procps \
+    ca-certificates \
+    supervisor \
+    libsodium-dev \
+    libbrotli-dev \
+    locales \
+    # Custom packages
+    nano zip unzip gnupg software-properties-common rsync \
+    ffmpeg automake build-essential libasound2-dev libpulse-dev lame \
+    jpegoptim optipng pngquant gifsicle webp libavif-bin \
+    # Local dev packages
+    gnupg2 sqlite3 libcap2-bin libpng-dev dnsutils librsvg2-bin fswatch \
+    # Stuff for building with Byond
+    gcc-multilib lib32stdc++6 zlib1g-dev:i386 libssl-dev:i386 pkg-config:i386 libstdc++6 libstdc++6:i386 libcurl4:i386 \
+    # Install PHP extensions
+    && install-php-extensions \
+    bz2 \
+    pcntl \
+    mbstring \
+    bcmath \
+    sockets \
+    pgsql \
+    pdo_pgsql \
+    opcache \
+    exif \
+    pdo_mysql \
+    zip \
+    intl \
+    gd \
+    redis \
+    rdkafka \
+    memcached \
+    igbinary \
+    ldap \
+    swoole \
+    uv \
+    vips \
+    excimer \
+    xdebug \
+    # Clean up
+    && apt-get -y autoremove \
+    && apt-get clean \
+    && docker-php-source delete \
+    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
+    && rm /var/log/lastlog /var/log/faillog \
+    # Supercronic
+    && arch="$(uname -m)" \
+    && case "$arch" in \
+    armhf) _cronic_fname='supercronic-linux-arm' ;; \
+    aarch64) _cronic_fname='supercronic-linux-arm64' ;; \
+    x86_64) _cronic_fname='supercronic-linux-amd64' ;; \
+    x86) _cronic_fname='supercronic-linux-386' ;; \
+    *) echo >&2 "error: unsupported architecture: $arch"; exit 1 ;; \
+    esac \
+    && wget -q "https://github.com/aptible/supercronic/releases/download/v0.2.29/${_cronic_fname}" -O /usr/bin/supercronic \
+    && chmod +x /usr/bin/supercronic \
+    && mkdir -p /etc/supercronic \
+    && echo "*/1 * * * * php ${ROOT}/artisan schedule:run --no-interaction" > /etc/supercronic/laravel
 
 # Set the locale
 RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && \
     locale-gen
 ENV LANG=en_US.UTF-8 \ LANGUAGE=en_US \ LC_ALL=en_US.UTF-8
 
-# Supercronic
-RUN wget -q "https://github.com/aptible/supercronic/releases/download/v0.2.29/supercronic-linux-amd64" -O /usr/bin/supercronic \
-    && chmod +x /usr/bin/supercronic \
-    && mkdir -p /etc/supercronic \
-    && echo "*/1 * * * * php ${ROOT}/artisan schedule:run --no-interaction" > /etc/supercronic/laravel
-
-RUN setcap "cap_net_bind_service=+ep" /usr/bin/php8.4
-
-RUN groupadd --force -g $WWWGROUP sail
-RUN useradd -ms /bin/bash --no-user-group -g $WWWGROUP -u $WWWUSER sail
-
-# Node stuff via NVM
-USER sail
-SHELL ["/bin/bash", "--login", "-c"]
-ENV NVM_DIR /home/sail/.nvm
-RUN curl https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash && \
-    . $NVM_DIR/nvm.sh && \
-    nvm install node && \
-    nvm use default && \
-    npm install -g npm pnpm bun yarn
-USER root
+# Create user
+RUN groupadd --force -g ${WWWGROUP} ${USER} \
+    && useradd -ms /bin/bash --no-log-init --no-user-group -g ${WWWGROUP} -u ${WWWUSER} ${USER} \
+    && chown -R ${WWWUSER}:${WWWGROUP} ${ROOT} /var/{log,run} \
+    && chmod -R a+rw ${ROOT} /var/{log,run} \
+    && cp ${PHP_INI_DIR}/php.ini-production ${PHP_INI_DIR}/php.ini
 
 ###########################################
-# Custom stuff
+# Custom root packages
 ##########################################
 
-# Github "gh"
-RUN mkdir -p -m 755 /etc/apt/keyrings \
-    && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
-    && cat $out | tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
-    && chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
-    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
-    && apt update \
-    && apt install gh -y \
-    && gh alias set -s run-watch 'gh workflow run $1 && sleep 3 && gh run list --json databaseId --workflow $1 -L 1 -q ".[0].databaseId" | xargs -I {} gh run watch {}'
+# Youtube-DLP
+ADD --chown=${WWWUSER}:${WWWGROUP} --chmod=0755 https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp /usr/local/bin/
 
-# Youtube DLP
-RUN curl -fsSL https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp && \
-    chmod a+rwx /usr/local/bin/yt-dlp
-
-## Dectalk
+# Dectalk
 RUN cd /usr/local/src && \
     curl -fsSL https://github.com/dectalk/dectalk/releases/download/2023-10-30/ubuntu-latest.tar.gz -o dectalk.tar.gz && \
     mkdir dectalk && \
@@ -99,20 +129,32 @@ RUN cd /usr/local/src && \
     chmod -R +x dectalk && \
     ln -s /usr/local/src/dectalk/say /usr/local/bin/dectalk
 
-# Packages for compiling the game with Byond
-RUN dpkg --add-architecture i386 && \
-    apt-get update && \
-    apt-get install -y rsync gcc-multilib lib32stdc++6 zlib1g-dev:i386 libssl-dev:i386 pkg-config:i386 libstdc++6 libstdc++6:i386 libcurl4:i386
+# Github "gh"
+# RUN mkdir -p -m 755 /etc/apt/keyrings \
+#     && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
+#     && cat $out | tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
+#     && chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
+#     && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
+#     && apt update \
+#     && apt install gh -y \
+#     && gh alias set -s run-watch 'gh workflow run $1 && sleep 3 && gh run list --json databaseId --workflow $1 -L 1 -q ".[0].databaseId" | xargs -I {} gh run watch {}'
 
-# Clean up apt cache
-RUN apt-get -y autoremove && \
-    apt-get clean && \
-    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
+##########################################
 
-COPY start-container /usr/local/bin/start-container
-COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
-COPY php.ini /etc/php/8.4/cli/conf.d/99-sail.ini
-RUN chmod +x /usr/local/bin/start-container
+COPY --link --chown=${WWWUSER}:${WWWGROUP} --from=vendor /usr/bin/composer /usr/bin/composer
+COPY --link --chown=${WWWUSER}:${WWWGROUP} --from=node /usr/local/bin /usr/local/bin
+COPY --link --chown=${WWWUSER}:${WWWGROUP} --from=node /usr/local/lib/node_modules /usr/local/lib/node_modules
+COPY --link --chown=${WWWUSER}:${WWWGROUP} --from=node /opt /opt
+COPY --link --chown=${WWWUSER}:${WWWGROUP} --from=bun /usr/local/bin/bun /usr/local/bin/
+COPY --link --chown=${WWWUSER}:${WWWGROUP} --from=bun /usr/local/bin/bunx /usr/local/bin/
+
+###########################################
+
+USER ${USER}
+
+COPY --link --chown=${WWWUSER}:${WWWGROUP} supervisord.conf /etc/supervisor/conf.d/supervisord.conf
+COPY --link --chown=${WWWUSER}:${WWWGROUP} php.ini ${PHP_INI_DIR}/conf.d/99-sail.ini
+COPY --link --chown=${WWWUSER}:${WWWGROUP} --chmod=755 start-container /usr/local/bin/start-container
 
 EXPOSE 80/tcp
 
